#MakeFile example

#target: dependency1 dependency2 ...
#	<tab> command

#NOTE: remember to add the TAB character before the command part

#Typing 'make' will invoke the first target entry in the file
encode: encode.cpp
	g++ -std=c++0x -o encode encode.cpp
decode: decode.cpp
	g++ -std=c++0x -o decode decode.cpp